[package]
name = "bioserde"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
prost = "0.10.1"
prost-types = "0.10.1"

[build-dependencies]
prost-build = "0.10.1"

[dev-dependencies]
criterion = "0.3.5"
#Specifically For Bechmarking
noodles = { version = "0.24.0", features = ["bed", "fastq","core"] }

[[bench]]
name = "example"
harness = false