[package]
name = "bioserde"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1"
prost = "0.10.1"
prost-types = "0.10.1"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0"

[build-dependencies]
prost-build = "0.10.1"